- google-cloud-spanner-change-archiver/src/test/java/com/google/cloud/spanner/archiver/it/ITArchiverTest.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToAvro.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisherTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisherTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerToAvroTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerDatabaseChangeEventPublisherTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerTableChangeEventPublisherTest.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/Example.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseChangeWatcher.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableChangeWatcher.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/TableId.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/AbstractMockServerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerTableTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerDatabaseTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerTest.java
Using ApiService as a common interface for change watchers and publishers ensures that users have a consistent interface for starting, stopping and managing the services offered by the library. These also automatically include error handling and asynchronous start and stop.
Fixes #1
> refactor: model all services as ApiService

- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/Samples.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/TableId.java
* Adds javadoc to public classes and methods.
* Reduces visibility of classes and methods where possible.
* Marks internal public classes as `@InternalApi`
> docs: add javadoc to public classes and methods

- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Configuration.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/PubsubHelper.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Samples.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSamplesTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/PubsubTestHelper.java
`google-cloud-change-publisher` can now automatically create the Pubsub topic(s) that are needed.
Fixes #20
> feat: create topics if not exist

- .circleci/config.yml
- google-cloud-spanner-change-publisher/pom.xml
- pom.xml
Run CI jobs every night to prevent changes in the Spanner client that might break spanner-change-watcher from going unnoticed.
> chore: run CI nightly

- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseChangeWatcher.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableChangeWatcher.java
Adds information on the ordering of callbacks and publish messages.
> docs: add information on ordering of callbacks

- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java
Fixes race conditions in the test where the `latch.countDown()` was executed before increasing the row count, causing flaky failures.
> test: first inc row count then latch count down

- .circleci/config.yml
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerTableTailerTest.java
- pom.xml
- samples/spanner-change-watcher-samples/src/main/java/com/google/cloud/spanner/watcher/sample/Samples.java
- samples/spanner-change-watcher-samples/src/test/java/com/google/cloud/spanner/watcher/sample/it/ITSamplesTest.java
Adds support for tables that contain multiple columns with the `allow_commit_timestamp=true` option.
Fixes #34
> feat: add support for multiple commit timestamp columns

- .circleci/config.yml
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerDatabaseTailerStressTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerStressTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/StressIntegrationTest.java
- pom.xml
The integration tests should be executed in parallel where that is possible. In addition, the stress tests should only be executed during the nightly build, and not for the PRs to reduce build time.
Fixes #43
> build: execute integration tests in parallel

- README.md
- google-cloud-spanner-change-publisher/README.md
- google-cloud-spanner-change-watcher/README.md
Adds documentation on the limitations to the different readme files, and a link to the Medium articles on how to use this framework.
> docs: add limitations to readme files

- google-cloud-spanner-change-archiver/src/main/resources/go/go.mod
The Go 1.11 runtime on Cloud Functions will be deprecated on August 5, 2020.
> Update Archiver Go version from 1.11 to 1.13.

- README.md
- google-cloud-spanner-change-watcher/README.md
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/DatabaseClientWithChangeSets.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseChangeSetPoller.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableChangeSetPoller.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerDatabaseChangeSetPollerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableChangeSetPollerTest.java
- samples/spanner-change-watcher-samples/src/main/java/com/google/cloud/spanner/watcher/sample/Samples.java
- samples/spanner-change-watcher-samples/src/test/java/com/google/cloud/spanner/watcher/sample/it/ITSamplesTest.java
Having a commit timestamp column directly in a data table that is updated during each transaction can be a breaking change for some applications, as a commit timestamp column that is updated using the PENDING_COMMIT_TIMESTAMP()
function will cause the owning table to no longer be readable during the remainder of the transaction. In addition to this limitation, it is also hard to efficiently index a commit timestamp column, which again can make polling a data table for changes inefficient.
This change allows users to create a change set table that keeps track of the change sets (transactions) that have been executed. Each table that is to be watched for changes reference these change sets through an id column.
This id column can easily be indexed, as it does not contain a monotonically …
> feat: add change set pollers

- .circleci/config.yml
- google-cloud-spanner-change-archiver/pom.xml
- google-cloud-spanner-change-publisher/pom.xml
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToAvroFactory.java
- google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToJsonFactory.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisherTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerToAvroTest.java
- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerToJsonTest.java
- google-cloud-spanner-change-watcher/pom.xml
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseChangeSetPoller.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/RandomResultSetGenerator.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerStressTest.java
- pom.xml
- samples/spanner-change-publisher-samples/pom.xml
- samples/spanner-change-watcher-samples/pom.xml
Adds support for `NUMERIC` to Cloud Spanner Change Watcher.
Fixes #56
> feat: add support for NUMERIC data type

- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/NotNullShardProvider.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/AbstractMockServerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerTableTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerTest.java
Adds support for:
* Shard columns that can contain any non-null value: The table poller will only select the rows that have a non-null value. The shard and commit timestamp columns can be included in a `NULL_FILTERED` secondary index that can be used by the poll query. Shard values for rows that have not recently been updated can also be set to null by a different process to keep the secondary index as small as possible.
* Table hints: Add a table hint such as `@{FORCE_INDEX=SecondaryIndex}` to force the poll query to use a secondary index.
Fixes #65
> feat: add NotNullShardProvider and support for table hints

- google-cloud-spanner-change-archiver/pom.xml
- google-cloud-spanner-change-publisher/pom.xml
- google-cloud-spanner-change-watcher/pom.xml
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/DatabaseClientWithChangeSets.java
- pom.xml
- samples/spanner-change-publisher-samples/pom.xml
- samples/spanner-change-watcher-samples/pom.xml
* Updates Spanner client library version to 3.3.2 from 2.x.
* Bumps own major version from 0 to 1 as Spanner has a major version bump.
> deps: bump Spanner version to 3.3.2

- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/AbstractMockServerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java
- google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerTableTailerTest.java
Support setting a limit for a poll query. This can increase efficiency of polling of tables that receive a very high rate of writes, as each poll will be smaller and consume less resources, but will be executed more often.
> feat: support limit clause in poll query

- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/FixedShardProvider.java
- google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java
Support array values for FixedShardProvider to allow a watcher to watch multiple shards of a table, or even all shards. Specifying a fixed list of shard values to use is more efficient than not specifying any values at all for a shard column that is included in a secondary index.
> feat: support array values for FixedShardProvider

- google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisherTest.java
Count down latch after registering the received message to prevent flaky test failures.
Fixes this flaky failure: https://app.circleci.com/pipelines/github/cloudspannerecosystem/spanner-change-watcher/464/workflows/25eed194-208a-4511-a4c0-8d40134b6ed3/jobs/470
> test: countdown latch after registering received message

- samples/spanner-change-watcher-samples/src/main/java/com/google/cloud/spanner/watcher/sample/Samples.java
- samples/spanner-change-watcher-samples/src/test/java/com/google/cloud/spanner/watcher/sample/it/ITSamplesTest.java
Some nightly builds have failed lately due to timeouts in the sample tests. This change increases the timeout values to what should be a safe value.
> test: increase timeouts for sample tests

- README.md
Adds the released Cloud Spanner change streams documentation link in the README to warn users that full support is available now.
> docs: add official change streams link in README

- README.md
- google-cloud-spanner-change-publisher/README.md
- google-cloud-spanner-change-watcher/README.md
Adds a limitation to the READMEs that PostgreSQL databases are not supported.
> docs: add limitation for PostgreSQL databases

- .circleci/config.yml
Use a fixed test instance instead of trying to create and drop an instance for each test run.
> build: use a fixed test instance
