cloudspannerecosystem/spanner-change-watcher

google-cloud-spanner-change-archiver/pom.xml, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-watcher/pom.xml, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerTableTailerTest.java, pom.xml
Import BOM instead of manually managing dependencies.
=> deps: import bom instead of self managing deps

google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Samples.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java
Adds javadoc and samples for spanner-change-publishers.
=> docs: adds javadoc and samples for publishers

google-cloud-spanner-change-archiver/src/test/java/com/google/cloud/spanner/archiver/it/ITArchiverTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerDatabaseChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerTableChangeEventPublisherTest.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/Samples.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSamplesTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerDatabaseTailerStressTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerDatabaseTailerTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerStressTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/SpannerTestHelper.java
Adds integration tests for all samples for spanner-change-watcher.
=> Sample i ts

google-cloud-spanner-change-archiver/src/test/java/com/google/cloud/spanner/archiver/it/ITArchiverTest.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Samples.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToAvro.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSamplesTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerDatabaseChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerTableChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/PubsubTestHelper.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSamplesTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/SpannerTestHelper.java
Adds integration tests for spanner-change-publisher samples.
=> tests: added integration tests for publisher samples

google-cloud-spanner-change-archiver/src/test/resources/logging.properties, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/resources/logging.properties, google-cloud-spanner-change-watcher/pom.xml, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseChangeWatcher.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java, google-cloud-spanner-change-watcher/src/test/resources/logging.properties, pom.xml
Cleans up logging and adds a test config.
=> logging: clean up logging and add test config

google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/Samples.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailer.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/AbstractMockServerTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java
=> fix: DatabaseTailer should fail if no tables were found

google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/PubsubHelper.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/MockPubSubServer.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerDatabaseChangeEventPublisherTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITSpannerTableChangeEventPublisherTest.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerDatabaseTailerTest.java, pom.xml
=> fix: publisher should test whether topic exists

google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java
=> fix: commit ts table should be created only once

google-cloud-spanner-change-publisher/README.md, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Configuration.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Main.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Samples.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/resources/scep.properties.example, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/MainTest.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/it/ITMainTest.java, google-cloud-spanner-change-publisher/src/test/resources/test-credentials.json, google-cloud-spanner-change-watcher/README.md, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java, pom.xml
=> feat: add run config for publisher

README.md
=> docs: add sample usage to root readme

.circleci/config.yml, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/Configuration.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerTableChangeEventPublisher.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/MainTest.java
=> build: setup circleci

google-cloud-spanner-change-archiver/src/test/java/com/google/cloud/spanner/archiver/it/ITArchiverTest.java, google-cloud-spanner-change-archiver/src/test/java/com/google/cloud/spanner/archiver/it/ITUploaderTest.java
Adds google-cloud-spanner-change-archiver integration tests.
=> tests: enable archiver integration tests

.circleci/config.yml, pom.xml
Updates Spanner to 1.57.0 snapshot.
=> deps: update to Spanner 1.57.0

README.md, google-cloud-spanner-change-archiver/README.md, google-cloud-spanner-change-archiver/pom.xml, google-cloud-spanner-change-publisher/README.md, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-watcher/README.md, google-cloud-spanner-change-watcher/pom.xml, pom.xml, samples/spanner-change-publisher-samples/pom.xml, samples/spanner-change-watcher-samples/pom.xml
=> release: release version 0.1.0

samples/spanner-change-publisher-samples/src/test/java/com/google/cloud/spanner/publisher/sample/it/ITSamplesTest.java
Fixes https://app.circleci.com/pipelines/github/cloudspannerecosystem/spanner-change-watcher/114/workflows/36330ad6-4cab-4d33-97c4-9185981bf8cb/jobs/119
=> test: increase timeout to prevent flaky failures

.circleci/config.yml, google-cloud-spanner-change-archiver/pom.xml, google-cloud-spanner-change-publisher/README.md, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-watcher/README.md, google-cloud-spanner-change-watcher/pom.xml, pom.xml, samples/spanner-change-publisher-samples/README.md, samples/spanner-change-publisher-samples/pom.xml, samples/spanner-change-watcher-samples/README.md, samples/spanner-change-watcher-samples/pom.xml
Prepares the project for publication on Maven central.
=> chore: prepare to publish to maven central

google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerDatabaseChangeEventPublisherTest.java
Fixes the test error in https://app.circleci.com/pipelines/github/cloudspannerecosystem/spanner-change-watcher/206/workflows/0da24c04-36c2-4ae4-a10b-f668a2b86169/jobs/211
=> fix: increase test wait to prevent flakiness

samples/spanner-change-publisher-samples/pom.xml
Fixes #61 
> It's a good idea to open an issue first for discussion.
- [x ] Tests pass
- [ x] Appropriate changes to README are included in PR
=> Adding a transform section to address runtime failures

samples/spanner-change-watcher-samples/src/main/java/com/google/cloud/spanner/watcher/sample/Samples.java, samples/spanner-change-watcher-samples/src/test/java/com/google/cloud/spanner/watcher/sample/it/ITSamplesTest.java
Adds sample and test for `NotNullShardProvider`.
=> docs: add sample for NotNullShardProvider

pom.xml
=> chore: use Google-specific endpoint

google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/SpannerUtilsTest.java
=> fix: include NUMERIC column in key builder

google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToAvroFactory.java, google-cloud-spanner-change-publisher/src/main/java/com/google/cloud/spanner/publisher/SpannerToJsonFactory.java, google-cloud-spanner-change-publisher/src/test/java/com/google/cloud/spanner/publisher/SpannerToAvroTest.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/DatabaseClientWithChangeSets.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerCommitTimestampRepository.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerTableTailer.java, google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/SpannerUtils.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/RandomResultSetGenerator.java, google-cloud-spanner-change-watcher/src/test/java/com/google/cloud/spanner/watcher/it/ITSpannerTableTailerStressTest.java, pom.xml
Adds support for JSON columns to Spanner Change Watcher and Spanner Change Publisher.
Fixes #74
=> feat: add support for JSON data type

google-cloud-spanner-change-archiver/pom.xml, google-cloud-spanner-change-publisher/README.md, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-watcher/README.md, google-cloud-spanner-change-watcher/pom.xml, pom.xml, samples/spanner-change-publisher-samples/pom.xml, samples/spanner-change-watcher-samples/README.md, samples/spanner-change-watcher-samples/pom.xml
=> release: version 1.2.0

google-cloud-spanner-change-archiver/pom.xml, google-cloud-spanner-change-publisher/README.md, google-cloud-spanner-change-publisher/pom.xml, google-cloud-spanner-change-watcher/README.md, google-cloud-spanner-change-watcher/pom.xml, pom.xml, samples/spanner-change-publisher-samples/pom.xml, samples/spanner-change-watcher-samples/README.md, samples/spanner-change-watcher-samples/pom.xml
- Updates Avro 1.9.2 -> 1.11.0
- Updates Gax 1.60.1 -> 1.67.0
- Updates libraries-bom 24.1.0 -> 24.1.1
=> deps: update avro to 1.11
